### ISSUE TITLE
สร้าง ui 

### ISSUE THREAD

**Issue by thanabordeee** [thanabordeee/Project-Scracth#10]

**Comment by AdisornSjr** [comment]
[ปก.zip](https://github.com/thanabordeee/Project-Scracth/files/9577085/default.zip)
หน้าเริ่มเกม

**Comment by AdisornSjr** [comment]
![Uploading Preview.png…]()

**Comment by AdisornSjr** [comment]
![Preview](https://user-images.githubusercontent.com/110969563/190473512-b6262f17-c8df-4984-b1d0-6e5a12948311.png)

**Comment by AdisornSjr** [comment]
![main](https://user-images.githubusercontent.com/110969563/190917255-256187e8-21c0-4432-b8a2-c3fb82d3060f.png)

**Comment by AdisornSjr** [comment]
![how to play](https://user-images.githubusercontent.com/110969563/190917261-8a5f7cd0-2605-46c2-88f2-a247b954adee.png)how to play

**Comment by AdisornSjr** [comment]
[Setting.zip](https://github.com/thanabordeee/Project-Scracth/files/9594396/Setting.zip)

**Comment by PAWEENNUTpuyfai** [comment]
เสร็จเรียบร้อย
