### ISSUE TITLE
สร้าวตัวละครหลัก(จนเสร็จสมบูรณ์)

### ISSUE THREAD

**Issue by thanabordeee** [thanabordeee/Project-Scracth#11]

**Comment by AdisornSjr** [comment]
![1](https://user-images.githubusercontent.com/110969563/190473616-067bd2b0-c48c-497e-bbe5-c5785a8c535f.png)
![2](https://user-images.githubusercontent.com/110969563/190473623-0fdfef73-bd72-4cbe-906c-623f4668a688.png)
![3](https://user-images.githubusercontent.com/110969563/190473626-fa3ea50f-3b83-4660-84ba-540de780665a.png)
Slime

**Comment by AdisornSjr** [comment]
![bat 1](https://user-images.githubusercontent.com/110969563/190473692-99f07f7f-3d64-481a-9a9f-0da6572f5e69.png)
![bat 2](https://user-images.githubusercontent.com/110969563/190473696-026b8bea-fd74-491b-8541-dec1adf502aa.png)
bat

**Comment by AdisornSjr** [comment]
![หลัง](https://user-images.githubusercontent.com/110969563/190473748-6963bef4-1c69-4183-b326-c3c35e00a409.png)
ตัวหลักเพิ่มตอนหันหลัง

**Comment by AdisornSjr** [comment]
[Slash v2.zip](https://github.com/thanabordeee/Project-Scracth/files/9577798/Slash.v2.zip)
การตีของตัวหลัก

**Comment by AdisornSjr** [comment]
![หน้า 1](https://user-images.githubusercontent.com/110969563/190917192-d9b4a11e-5289-47f6-a65c-1e9bb534ff43.png)
![หน้า 2](https://user-images.githubusercontent.com/110969563/190917194-9eda47b1-45f4-4da1-b4b5-523d659a3fd2.png)

**Comment by AdisornSjr** [comment]
![หลัง 1](https://user-images.githubusercontent.com/110969563/190917198-b6018204-f96b-4424-bb03-e3c0ee6d1e3f.png)
![หลัง 2](https://user-images.githubusercontent.com/110969563/190917200-ef07da60-5937-4314-abc7-2760ac25c17b.png)
