### ISSUE TITLE
สร้างฉากหลัง(จนเสร็จสมบูรณฺ์)

### ISSUE THREAD

**Issue by thanabordeee** [thanabordeee/Project-Scracth#12]

**Comment by AdisornSjr** [comment]
![preview](https://user-images.githubusercontent.com/110969563/190473840-9f61fc8b-0476-45da-a62d-fe32c5b42a02.png)
ด่าน 1

**Comment by AdisornSjr** [comment]
[Map 1.zip](https://github.com/thanabordeee/Project-Scracth/files/9577751/Map.1.zip)
object map 1

**Comment by AdisornSjr** [comment]
![2](https://user-images.githubusercontent.com/110969563/190474009-401bea5f-9d3d-4b97-9274-bd33eee3d46e.png)
ด่าน 2

**Comment by AdisornSjr** [comment]
![preview](https://user-images.githubusercontent.com/110969563/190705091-6bddd15a-4c2e-402a-9192-df71985fda08.png)
ด่าน 3

**Comment by AdisornSjr** [comment]
![preview](https://user-images.githubusercontent.com/110969563/190707005-9d986df8-64f0-4ca1-9994-ec7efde72652.png)
4

**Comment by AdisornSjr** [comment]
![5](https://user-images.githubusercontent.com/110969563/190707045-8740aad9-d74d-4b5b-a27e-b1367d4ead2b.png)
final boss

**Comment by PAWEENNUTpuyfai** [comment]
ทำทุกด่านครบเรียบร้อยแล้ว
