### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by AdisornSjr** [thanabordeee/Project-Scracth#15]

**Comment by AdisornSjr** [comment]
[Uploading 1st.zip…]()
เสียงแยกเป็น 2 ไฟล์นะ

**Comment by AdisornSjr** [comment]
[Uploading 2nd half.zip…]()

**Comment by AdisornSjr** [comment]
[slash eff.zip](https://github.com/thanabordeee/Project-Scracth/files/9582859/slash.eff.zip)
Slah sound effect

**Comment by AdisornSjr** [comment]
[1st.zip](https://github.com/thanabordeee/Project-Scracth/files/9609509/1st.zip)

**Comment by AdisornSjr** [comment]
[2nd half.zip](https://github.com/thanabordeee/Project-Scracth/files/9609512/2nd.half.zip)

**Comment by AdisornSjr** [comment]
4 7 9

**Comment by AdisornSjr** [comment]
[Door open.zip](https://github.com/thanabordeee/Project-Scracth/files/9609776/Door.open.zip)

**Comment by thanabordeee** [comment]
[metal-small1.zip](https://github.com/thanabordeee/Project-Scracth/files/9609821/metal-small1.zip)

**Comment by AdisornSjr** [comment]
[dead.zip](https://github.com/thanabordeee/Project-Scracth/files/9609861/dead.zip)

**Comment by thanabordeee** [comment]
[victory.zip](https://github.com/thanabordeee/Project-Scracth/files/9609879/victory.zip)

**Comment by thanabordeee** [comment]
[dead.zip](https://github.com/thanabordeee/Project-Scracth/files/9609883/dead.zip)

**Comment by AdisornSjr** [comment]
[boss slamm.zip](https://github.com/thanabordeee/Project-Scracth/files/9609914/boss.slamm.zip)

**Comment by AdisornSjr** [comment]
[victory.zip](https://github.com/thanabordeee/Project-Scracth/files/9610012/victory.zip)

**Comment by PAWEENNUTpuyfai** [comment]
ใส่เพลงเสร็จเรียบร้อย
