### ISSUE TITLE
เขียนโปรแกรม ตัวละครหลัก(บางส่วน)

### ISSUE THREAD

**Issue by thanabordeee** [thanabordeee/Project-Scracth#4]

**Comment by pannawit12** [comment]
https://user-images.githubusercontent.com/110965510/189022794-72d5ae92-4c86-42c5-8a58-40fb618787dc.mp4

เดิน

**Comment by pannawit12** [comment]
https://user-images.githubusercontent.com/110965510/189184534-80555d62-d782-4192-8662-439a7180ea13.mp4

ชนสิ่งกีดขวางแล้วไม่ทะลุผ่าน
