### ISSUE TITLE
สร้างฉากหลัง(บางส่วน)

### ISSUE THREAD

**Issue by thanabordeee** [thanabordeee/Project-Scracth#6]

**Comment by AdisornSjr** [comment]
[map'.zip](https://github.com/thanabordeee/Project-Scracth/files/9507801/map.zip)

ตอนนี้ได้ทำฉากหลังมาบางส่วนแล้ว

**Comment by AdisornSjr** [comment]
![ASA](https://user-images.githubusercontent.com/110969563/188925853-fef912fa-fa88-4bda-92ba-a27bec4ace51.png)

เป็นแนวประมาณนี้

**Comment by AdisornSjr** [comment]
![Key](https://user-images.githubusercontent.com/110969563/189198211-a5557fba-fd79-493e-a9f6-1d03b9837339.png)
กุญแจ

**Comment by AdisornSjr** [comment]
[MAP.zip](https://github.com/thanabordeee/Project-Scracth/files/9550049/MAP.zip)
update ของใน map

**Comment by AdisornSjr** [comment]
![Preview](https://user-images.githubusercontent.com/110969563/189889022-708113d3-e111-445b-822c-1bc991fce4d9.png)
หน้าตอนเริ่มเกม 01

**Comment by AdisornSjr** [comment]
[ปก.zip](https://github.com/thanabordeee/Project-Scracth/files/9556556/default.zip)
สิ่งของใน หน้าเริ่มเกม

**Comment by thanabordeee** [comment]
ภาพด่านที่1คร่าวๆ
![map1(adjust)](https://user-images.githubusercontent.com/110457187/189925485-aa909790-6b99-4401-b2ad-e4b72d25fc8e.jpg)

**Comment by thanabordeee** [comment]
![Map2](https://user-images.githubusercontent.com/110457187/189925569-b62e1527-83d6-4803-bc1f-13f7087900c1.jpg)
ภาพแมพที่2

**Comment by AdisornSjr** [comment]
[Object.zip](https://github.com/thanabordeee/Project-Scracth/files/9558841/Object.zip)
พวก object update ใหม่นะๆๆ
