### ISSUE TITLE
สร้างตัวละครหลัก(บางส่วน)

### ISSUE THREAD

**Issue by thanabordeee** [thanabordeee/Project-Scracth#7]

**Comment by AdisornSjr** [comment]
![ตัวหลัก](https://user-images.githubusercontent.com/110969563/188924558-6514caa7-7524-4a8e-aaa0-21cddfa9a1d3.png)

Main Character 01 tester

**Comment by AdisornSjr** [comment]
[อัศวิน.zip](https://github.com/thanabordeee/Project-Scracth/files/9550181/default.zip)
update ตัวละครหลัก
